# automatically generated by the FlatBuffers1 compiler, do not modify

# namespace: Grocery

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class bottles(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # bottles
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # bottles
    def Sprite(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # bottles
    def AppleJuice(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # bottles
    def OrangeJuice(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def Createbottles(builder, sprite, appleJuice, orangeJuice):
    builder.Prep(4, 12)
    builder.PrependUint32(orangeJuice)
    builder.PrependUint32(appleJuice)
    builder.PrependUint32(sprite)
    return builder.Offset()
