# automatically generated by the FlatBuffers1 compiler, do not modify

# namespace: Grocery

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class milk1(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # milk1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # milk1
    def Type(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # milk1
    def Quality(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def Createmilk1(builder, type, quality):
    builder.Prep(4, 8)
    builder.PrependUint32(quality)
    builder.Pad(2)
    builder.PrependInt16(type)
    return builder.Offset()
