# automatically generated by the FlatBuffers1 compiler, do not modify

# namespace: Grocery

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class bread1(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # bread1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # bread1
    def Type(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # bread1
    def Quality(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def Createbread1(builder, type, quality):
    builder.Prep(4, 8)
    builder.PrependFloat32(quality)
    builder.Pad(2)
    builder.PrependInt16(type)
    return builder.Offset()
