# automatically generated by the FlatBuffers1 compiler, do not modify

# namespace: Grocery

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class cans(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # cans
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # cans
    def Beer(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # cans
    def Coke(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # cans
    def Coffee(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def Createcans(builder, beer, coke, coffee):
    builder.Prep(4, 12)
    builder.PrependUint32(coffee)
    builder.PrependUint32(coke)
    builder.PrependUint32(beer)
    return builder.Offset()
