# automatically generated by the FlatBuffers1 compiler, do not modify

# namespace: Grocery

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class drinks1(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # drinks1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # drinks1
    def Can(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # drinks1
    def Bottle(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def Createdrinks1(builder, can_beer, can_coke, can_coffee, bottle_sprite, bottle_appleJuice, bottle_orangeJuice):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependUint32(bottle_orangeJuice)
    builder.PrependUint32(bottle_appleJuice)
    builder.PrependUint32(bottle_sprite)
    builder.Prep(4, 12)
    builder.PrependUint32(can_coffee)
    builder.PrependUint32(can_coke)
    builder.PrependUint32(can_beer)
    return builder.Offset()
