# automatically generated by the FlatBuffers1 compiler, do not modify

# namespace: Grocery

class milk_type(object):
    oat = 0
    onePercent = 1
    twoPercent = 2
    fatFree = 3
    whole = 4
    almond = 5
    cashew = 6
